apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-pagamento-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
