apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-nuGETBurger-db-pvc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
          storage: 1Gi
